#!/bin/bash
# Edited by @ColtSeals
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Conectando ao NerdologiaVPS..."
sleep 2
echo "Checando Permissão..."
sleep 3
echo -e "${green}Permissão Aceita...${NC}"
sleep 2
clear

read -p "Nome de Usuario OPENVPN & SSH : " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
echo "Nome de usuario muito pequeno"
exit 0
else
read -p "Senha do Usuario : " password
read -p "Validade do Usuario: " masa_aktif
MYIP=$(wget -qO- ipv4.icanhazip.com)
today=`date +%s`
masa_aktif_detik=$(( $masa_aktif * 86400 ))
saat_expired=$(($today + $masa_aktif_detik))
tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')
clear
echo "Connectando ao @NerdologiaVPS..."
sleep 0.4
echo "Criando Conta..."
sleep 0.3
echo "Gerando Host..."
sleep 0.2
echo "Criando seu novo nome de usuário: $username"
sleep 0.2
echo "Criando senha para $username"
sleep 1


useradd $username
usermod -s /bin/false $username
usermod -e  $tanggal_expired $username
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  clear
  echo "Script Edited @ColtSeals"
  echo "Informações @NerdologiaVPS"
  echo " "
  echo "   Detalhes da nova conta criada"
  echo "---------------------------------------"
  echo "   Host            : $MYIP"
  echo "   Nome            : $username"
  echo "   Senha           : $password"
  echo "   Validade        : $masa_aktif Dias"
  echo "   Data Expiração  : $tanggal_expired_display"
  echo "   Porta           : 22,80,109,143,443"
  echo "--------------------------------------"
  echo " "
fi
